cargo-features = ["per-package-target"]

[package]
name = "kernel"
version = "0.1.0"
edition = "2024"
forced-target = "x86_64-unknown-none"

[dependencies]
limine = "0.3.1"
log = "0.4.25"
spin = "0.9.8"
